# Generated by Django 2.2.5 on 2019-09-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
