# Generated by Django 2.2.5 on 2019-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='type',
            field=models.CharField(choices=[('choice', 'choice'), ('number', 'number'), ('string', 'string')], max_length=30),
        ),
    ]
