# Generated by Django 2.2.5 on 2019-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190927_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='year_of_birth',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='drunk',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='smoked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
