# Generated by Django 2.2.5 on 2019-09-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
