# Generated by Django 2.2.5 on 2019-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
