# Generated by Django 2.2.5 on 2019-09-27 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190927_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('date_of_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Challenge')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='challenges',
            field=models.ManyToManyField(blank=True, related_name='customers', through='api.ChallengeChoice', to='api.Challenge'),
        ),
        migrations.AddField(
            model_name='challengechoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
    ]
