# Generated by Django 2.2.5 on 2019-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190928_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='year_of_birth',
            new_name='years',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='drunk',
        ),
        migrations.AddField(
            model_name='customer',
            name='do_sports',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='eat_fruits',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='heart_disease',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mass_index',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sleep_hours',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='smoked',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
