# Generated by Django 2.2.5 on 2019-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_stress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRecommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Challenge')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='variant',
        ),
        migrations.AddField(
            model_name='customer',
            name='diff_risk',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='challengerecommended',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='recommended_challenges',
            field=models.ManyToManyField(blank=True, related_name='recommended_customers', through='api.ChallengeRecommended', to='api.Challenge'),
        ),
    ]
