# Generated by Django 2.2.5 on 2019-09-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='recommended_challenges',
        ),
    ]
