# Generated by Django 2.2.5 on 2019-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customer_recommended_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='days',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='risk_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
