# Generated by Django 2.2.5 on 2019-09-28 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190928_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
